### ISSUE TITLE
Convert Email Text to Link conflicts with content in data attribute

### ISSUE THREAD

**Issue by daomapsieucap** [daomapsieucap/fiber-admin#11]
Convert Email Text to Link now converts all content using hook `the_content` which makes the wrong HTML structure in the `data-` attribute.

To prevent this issue, I think the feature Convert Email Text needs to use regex to prevent converting text in the `data-` attribute.

**Comment by daomapsieucap** [comment]
Suggest solutions:
- Update regex to replace email addresses that don't exist in data attribute: https://regex101.com/r/NDBXS9/1.
- Use the DOM to check and replace email addresses: https://stackoverflow.com/questions/2165381/how-can-i-replace-strings-not-within-a-link-tag

**Comment by zrvincent** [comment]
@daomapsieucap Have issue convert email with regex.
When element with a email structure attribute, and only 1 element is added on page. All content will not be wrapped with \<p> tag. So $att_email_regex regex not work. 
When there are more than 2 elements, all content will be wrapped with \<p> tag. But there is a problem if the element has more attributes, the regex doesn't work correctly

![content-01](https://user-images.githubusercontent.com/12256563/224226679-6394aad3-6eb4-42e2-ad8e-ca0f50b27a1d.png)
---
![content-03](https://user-images.githubusercontent.com/12256563/224226660-df054184-2f8e-41c6-aa19-c2ce59aca5de.png)
![content-02](https://user-images.githubusercontent.com/12256563/224226696-83043ff4-a2cd-46aa-a27d-39ec5ef92b33.png)

---

When the regex doesn't work correctly, the email structure attribute will be replaced with email link. Lead to incorrect email extraction results.

![convert-is-wrong-attribute-1](https://user-images.githubusercontent.com/12256563/224227835-439ed924-f861-4cc1-bf99-3cdf818fe2dc.png)
![convert-is-wrong-attribute-2](https://user-images.githubusercontent.com/12256563/224227850-62356968-5c01-40e9-8acd-e12acff7f2e7.png)
![convert-is-wrong-attribute](https://user-images.githubusercontent.com/12256563/224227864-e012f46d-2e89-4ba9-af4c-1e81c04d5e07.png)

---

I updated my code for function **fiad_auto_convert_email_address**. Demo on the lab site with **Team List component**. Please see demo and revise my code on the Lab site. https://lab.mochisandbox.com/test-bug-convert-email/

Link test Regex and preg_match:
- https://regex101.com/r/98DkBm/1
- https://www.phpliveregex.com/p/Ifx

**Comment by zrvincent** [comment]
@daomapsieucap Have issue convert email with regex.
When element with a email structure attribute, and only 1 element is added on page. All content will not be wrapped with \<p> tag. So $att_email_regex regex not work.
When there are more than 2 elements, all content will be wrapped with \<p> tag. But there is a problem if the element has more attributes, the regex doesn't work correctly

![content-01](https://user-images.githubusercontent.com/12256563/224252500-b1d749dd-3eff-4595-b864-2ec19ef5a1a6.png)
---
![content-03](https://user-images.githubusercontent.com/12256563/224252536-09dd9722-7cdb-4bf5-8652-f697f44c9a3b.png)
![content-02](https://user-images.githubusercontent.com/12256563/224252543-55519436-bf52-47ff-9f43-ed31f806e823.png)
---
When the regex doesn't work correctly, the email structure attribute will be replaced with email link. Lead to incorrect email extraction results.

![convert-is-wrong-attribute-1](https://user-images.githubusercontent.com/12256563/224252678-c2585a44-7c77-4bc2-846a-567dcdbf629c.png)
![convert-is-wrong-attribute-2](https://user-images.githubusercontent.com/12256563/224253734-b5e39d86-7993-4bd8-ad9d-379c78a7f4a1.png)
![convert-is-wrong-attribute](https://user-images.githubusercontent.com/12256563/224252750-b7ebc46f-32d7-4bc9-b71a-4da39a39f119.png)
---

I updated my code for function fiad_auto_convert_email_address. Demo on the lab site with Team List component. Please see demo on **test bug convert email** page and revise my code on the Lab site.

Link test Regex and preg_match:

https://regex101.com/r/1jhgsF/1
https://www.phpliveregex.com/p/IfC

**Comment by daomapsieucap** [comment]
@phongkhuu115 Could you help to check the case mentioned above?
