### ISSUE TITLE
Content protection

### ISSUE THREAD

**Issue by daomapsieucap** [daomapsieucap/fiber-admin#17]
At this time, Fiber Admin has 2 options for content protection:
- Image Protection: Disable right-click on the image.
- Content Protection: Prevent copy content.

I think it's better to merge these options into one but with conditional logic:
- We will have one option: `Disable content protection` (DCP).
- When the DCP option is disabled: Show the 2 options: Disable Image Protection and Disable Content Protection.

**Comment by daomapsieucap** [comment]
@zrvincent Please check my comment on https://github.com/daomapsieucap/fiber-admin/pull/23#issuecomment-1600018988

**Comment by zrvincent** [comment]
@daomapsieucap please review my commit for this issue.

**Comment by daomapsieucap** [comment]
After doing some research and checking the requirement carefully, I don't think we'll need separate options to disable Text protection & Image protection. It's better to just have only one option to just enable or disable the content protection completely so I modified the code following this option.
