### ISSUE TITLE
Convert email: Conflict with trailing slash in br tag

### ISSUE THREAD

**Issue by zrvincent** [daomapsieucap/fiber-admin#44]
I see issue with auto convert email link. When I input email and then  break line with new content, the email not is converted to email link.

![image](https://github.com/user-attachments/assets/92f87707-df0e-4445-8218-677877fe657f)

**Comment by zrvincent** [comment]
@daomapsieucap please help me fix this issue. 
I tried to change regex pattern to skip `<br>` but not working.
Tried to replace/re-add `<br>` tag before/after `preg_replace_callback`, but it didn't work.

**Comment by daomapsieucap** [comment]
This issue is fixed in https://github.com/daomapsieucap/fiber-admin/commit/c98492c42a372d6b765b1dde95ba5f42a8b22920
