### ISSUE TITLE
Coming soon / Maintenance mode

### ISSUE THREAD

**Issue by daomapsieucap** [daomapsieucap/fiber-admin#7]
> Add coming soon / maintenance mode

The idea for this feature can be listed below:
- Has the option to select a page for coming soon / maintenance mode (this page should be noindex as default)
- Coming soon & maintenance page don't have header & footer.
- Has extra fields for custom CSS / JS (with code style block if it's possible)
- **Coming soon / maintenance mode should have the correct response code**

**Comment by phongkhuu115** [comment]
@daomapsieucap From [Yoast SEO](https://yoast.com/http-503-site-maintenance-seo/#:~:text=The%20original%20definition%20of%20the,be%20alleviated%20after%20some%20delay.) about 503. I think using 503 status code for maintenance page is the best option.

**Comment by daomapsieucap** [comment]
Todo for @daomapsieucap :

- [ ] Revise code
- [ ] Make CSM compatible with all page builders.
- [ ] Use default CSS from WordPress for meta boxes layout (if it has).
- [ ] Encrypt / Un-encrypt JS setting for security.
- [ ] Testing.
