### ISSUE TITLE
Taxonomy Custom Order is not working

### ISSUE THREAD

**Issue by daomapsieucap** [daomapsieucap/fiber-admin#9]
When creating a new custom taxonomy term, the term order is not increased automatically anymore. Seem that it only happens on WordPress 6.0.

**Comment by zrvincent** [comment]
Warning: in_array() expects parameter 2 to be array, string given in /var/www/ceragres.mochisandbox.com/public_html/wp-content/plugins/fiber-admin/includes/cpo.php on line 228
---
Warning: Cannot modify header information - headers already sent by (output started at /var/www/ceragres.mochisandbox.com/public_html/wp-content/plugins/fiber-admin/includes/cpo.php:228) in /var/www/ceragres.mochisandbox.com/public_html/wp-includes/class-wp-ajax-response.php on line 152

**Comment by daomapsieucap** [comment]
@zrvincent Fixed with commit https://github.com/daomapsieucap/fiber-admin/commit/e9e5ddaeb2f696110ad72420c647bb0261372f73 and version https://github.com/daomapsieucap/fiber-admin/releases/tag/v2.0.10
